<?php
//Schema
$gretta = new \Doctrine\DBAL\Schema\Schema(
array(),
array(),
new \Doctrine\DBAL\Schema\SchemaConfig()
);

//Schema Sequences

//Tables
$columns_priv = $gretta->createTable('columns_priv');
$db = $gretta->createTable('db');
$event = $gretta->createTable('event');
$func = $gretta->createTable('func');
$general_log = $gretta->createTable('general_log');
$help_category = $gretta->createTable('help_category');
$help_keyword = $gretta->createTable('help_keyword');
$help_relation = $gretta->createTable('help_relation');
$help_topic = $gretta->createTable('help_topic');
$host = $gretta->createTable('host');
$ndb_binlog_index = $gretta->createTable('ndb_binlog_index');
$plugin = $gretta->createTable('plugin');
$proc = $gretta->createTable('proc');
$procs_priv = $gretta->createTable('procs_priv');
$proxies_priv = $gretta->createTable('proxies_priv');
$servers = $gretta->createTable('servers');
$slow_log = $gretta->createTable('slow_log');
$tables_priv = $gretta->createTable('tables_priv');
$time_zone = $gretta->createTable('time_zone');
$time_zone_leap_second = $gretta->createTable('time_zone_leap_second');
$time_zone_name = $gretta->createTable('time_zone_name');
$time_zone_transition = $gretta->createTable('time_zone_transition');
$time_zone_transition_type = $gretta->createTable('time_zone_transition_type');
$user = $gretta->createTable('user');
$users = $gretta->createTable('users');
$users_acadia = $gretta->createTable('users_acadia');

//Table Columns
$columns_priv->addColumn('Host', 'string', array('default'=>'','length'=>'60','notnull'=>true,'fixed'=>'1',));
$columns_priv->addColumn('Db', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$columns_priv->addColumn('User', 'string', array('default'=>'','length'=>'16','notnull'=>true,'fixed'=>'1',));
$columns_priv->addColumn('Table_name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$columns_priv->addColumn('Column_name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$columns_priv->addColumn('Timestamp', 'datetime', array('default'=>'CURRENT_TIMESTAMP','notnull'=>true,));
$columns_priv->addColumn('Column_priv', 'simple_array', array('default'=>'','notnull'=>true,));
$db->addColumn('Host', 'string', array('default'=>'','length'=>'60','notnull'=>true,'fixed'=>'1',));
$db->addColumn('Db', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$db->addColumn('User', 'string', array('default'=>'','length'=>'16','notnull'=>true,'fixed'=>'1',));
$db->addColumn('Select_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Insert_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Update_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Delete_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Create_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Drop_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Grant_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('References_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Index_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Alter_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Create_tmp_table_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Lock_tables_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Create_view_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Show_view_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Create_routine_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Alter_routine_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Execute_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Event_priv', 'string', array('default'=>'N','notnull'=>true,));
$db->addColumn('Trigger_priv', 'string', array('default'=>'N','notnull'=>true,));
$event->addColumn('db', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$event->addColumn('name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$event->addColumn('body', 'blob', array('notnull'=>true,));
$event->addColumn('definer', 'string', array('default'=>'','length'=>'77','notnull'=>true,'fixed'=>'1',));
$event->addColumn('execute_at', 'datetime', array('notnull'=>false,));
$event->addColumn('interval_value', 'integer', array('notnull'=>false,));
$event->addColumn('interval_field', 'string', array('notnull'=>false,));
$event->addColumn('created', 'datetime', array('default'=>'CURRENT_TIMESTAMP','notnull'=>true,));
$event->addColumn('modified', 'datetime', array('default'=>'0000-00-00 00:00:00','notnull'=>true,));
$event->addColumn('last_executed', 'datetime', array('notnull'=>false,));
$event->addColumn('starts', 'datetime', array('notnull'=>false,));
$event->addColumn('ends', 'datetime', array('notnull'=>false,));
$event->addColumn('status', 'string', array('default'=>'ENABLED','notnull'=>true,));
$event->addColumn('on_completion', 'string', array('default'=>'DROP','notnull'=>true,));
$event->addColumn('sql_mode', 'simple_array', array('default'=>'','notnull'=>true,));
$event->addColumn('comment', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$event->addColumn('originator', 'integer', array('unsigned'=>true,'notnull'=>true,));
$event->addColumn('time_zone', 'string', array('default'=>'SYSTEM','length'=>'64','notnull'=>true,'fixed'=>'1',));
$event->addColumn('character_set_client', 'string', array('length'=>'32','notnull'=>false,'fixed'=>'1',));
$event->addColumn('collation_connection', 'string', array('length'=>'32','notnull'=>false,'fixed'=>'1',));
$event->addColumn('db_collation', 'string', array('length'=>'32','notnull'=>false,'fixed'=>'1',));
$event->addColumn('body_utf8', 'blob', array('notnull'=>false,));
$func->addColumn('name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$func->addColumn('ret', 'boolean', array('default'=>'0','notnull'=>true,));
$func->addColumn('dl', 'string', array('default'=>'','length'=>'128','notnull'=>true,'fixed'=>'1',));
$func->addColumn('type', 'string', array('notnull'=>true,));
$general_log->addColumn('event_time', 'datetime', array('default'=>'CURRENT_TIMESTAMP','notnull'=>true,));
$general_log->addColumn('user_host', 'text', array('notnull'=>true,));
$general_log->addColumn('thread_id', 'integer', array('notnull'=>true,));
$general_log->addColumn('server_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$general_log->addColumn('command_type', 'string', array('length'=>'64','notnull'=>true,));
$general_log->addColumn('argument', 'text', array('notnull'=>true,));
$help_category->addColumn('help_category_id', 'smallint', array('unsigned'=>true,'notnull'=>true,));
$help_category->addColumn('name', 'string', array('length'=>'64','notnull'=>true,'fixed'=>'1',));
$help_category->addColumn('parent_category_id', 'smallint', array('unsigned'=>true,'notnull'=>false,));
$help_category->addColumn('url', 'string', array('length'=>'128','notnull'=>true,'fixed'=>'1',));
$help_keyword->addColumn('help_keyword_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$help_keyword->addColumn('name', 'string', array('length'=>'64','notnull'=>true,'fixed'=>'1',));
$help_relation->addColumn('help_keyword_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$help_relation->addColumn('help_topic_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$help_topic->addColumn('help_topic_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$help_topic->addColumn('name', 'string', array('length'=>'64','notnull'=>true,'fixed'=>'1',));
$help_topic->addColumn('help_category_id', 'smallint', array('unsigned'=>true,'notnull'=>true,));
$help_topic->addColumn('description', 'text', array('notnull'=>true,));
$help_topic->addColumn('example', 'text', array('notnull'=>true,));
$help_topic->addColumn('url', 'string', array('length'=>'128','notnull'=>true,'fixed'=>'1',));
$host->addColumn('Host', 'string', array('default'=>'','length'=>'60','notnull'=>true,'fixed'=>'1',));
$host->addColumn('Db', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$host->addColumn('Select_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Insert_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Update_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Delete_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Create_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Drop_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Grant_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('References_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Index_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Alter_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Create_tmp_table_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Lock_tables_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Create_view_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Show_view_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Create_routine_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Alter_routine_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Execute_priv', 'string', array('default'=>'N','notnull'=>true,));
$host->addColumn('Trigger_priv', 'string', array('default'=>'N','notnull'=>true,));
$ndb_binlog_index->addColumn('epoch', 'bigint', array('unsigned'=>true,'notnull'=>true,));
$ndb_binlog_index->addColumn('Position', 'bigint', array('unsigned'=>true,'notnull'=>true,));
$ndb_binlog_index->addColumn('File', 'string', array('length'=>'255','notnull'=>true,));
$ndb_binlog_index->addColumn('inserts', 'bigint', array('unsigned'=>true,'notnull'=>true,));
$ndb_binlog_index->addColumn('updates', 'bigint', array('unsigned'=>true,'notnull'=>true,));
$ndb_binlog_index->addColumn('deletes', 'bigint', array('unsigned'=>true,'notnull'=>true,));
$ndb_binlog_index->addColumn('schemaops', 'bigint', array('unsigned'=>true,'notnull'=>true,));
$plugin->addColumn('name', 'string', array('default'=>'','length'=>'64','notnull'=>true,));
$plugin->addColumn('dl', 'string', array('default'=>'','length'=>'128','notnull'=>true,));
$proc->addColumn('db', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$proc->addColumn('name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$proc->addColumn('type', 'string', array('notnull'=>true,));
$proc->addColumn('specific_name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$proc->addColumn('language', 'string', array('default'=>'SQL','notnull'=>true,));
$proc->addColumn('sql_data_access', 'string', array('default'=>'CONTAINS_SQL','notnull'=>true,));
$proc->addColumn('is_deterministic', 'string', array('default'=>'NO','notnull'=>true,));
$proc->addColumn('security_type', 'string', array('default'=>'DEFINER','notnull'=>true,));
$proc->addColumn('param_list', 'blob', array('notnull'=>true,));
$proc->addColumn('returns', 'blob', array('notnull'=>true,));
$proc->addColumn('body', 'blob', array('notnull'=>true,));
$proc->addColumn('definer', 'string', array('default'=>'','length'=>'77','notnull'=>true,'fixed'=>'1',));
$proc->addColumn('created', 'datetime', array('default'=>'CURRENT_TIMESTAMP','notnull'=>true,));
$proc->addColumn('modified', 'datetime', array('default'=>'0000-00-00 00:00:00','notnull'=>true,));
$proc->addColumn('sql_mode', 'simple_array', array('default'=>'','notnull'=>true,));
$proc->addColumn('comment', 'text', array('notnull'=>true,));
$proc->addColumn('character_set_client', 'string', array('length'=>'32','notnull'=>false,'fixed'=>'1',));
$proc->addColumn('collation_connection', 'string', array('length'=>'32','notnull'=>false,'fixed'=>'1',));
$proc->addColumn('db_collation', 'string', array('length'=>'32','notnull'=>false,'fixed'=>'1',));
$proc->addColumn('body_utf8', 'blob', array('notnull'=>false,));
$procs_priv->addColumn('Host', 'string', array('default'=>'','length'=>'60','notnull'=>true,'fixed'=>'1',));
$procs_priv->addColumn('Db', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$procs_priv->addColumn('User', 'string', array('default'=>'','length'=>'16','notnull'=>true,'fixed'=>'1',));
$procs_priv->addColumn('Routine_name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$procs_priv->addColumn('Routine_type', 'string', array('notnull'=>true,));
$procs_priv->addColumn('Grantor', 'string', array('default'=>'','length'=>'77','notnull'=>true,'fixed'=>'1',));
$procs_priv->addColumn('Proc_priv', 'simple_array', array('default'=>'','notnull'=>true,));
$procs_priv->addColumn('Timestamp', 'datetime', array('default'=>'CURRENT_TIMESTAMP','notnull'=>true,));
$proxies_priv->addColumn('Host', 'string', array('default'=>'','length'=>'60','notnull'=>true,'fixed'=>'1',));
$proxies_priv->addColumn('User', 'string', array('default'=>'','length'=>'16','notnull'=>true,'fixed'=>'1',));
$proxies_priv->addColumn('Proxied_host', 'string', array('default'=>'','length'=>'60','notnull'=>true,'fixed'=>'1',));
$proxies_priv->addColumn('Proxied_user', 'string', array('default'=>'','length'=>'16','notnull'=>true,'fixed'=>'1',));
$proxies_priv->addColumn('With_grant', 'boolean', array('default'=>'0','notnull'=>true,));
$proxies_priv->addColumn('Grantor', 'string', array('default'=>'','length'=>'77','notnull'=>true,'fixed'=>'1',));
$proxies_priv->addColumn('Timestamp', 'datetime', array('default'=>'CURRENT_TIMESTAMP','notnull'=>true,));
$servers->addColumn('Server_name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$servers->addColumn('Host', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$servers->addColumn('Db', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$servers->addColumn('Username', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$servers->addColumn('Password', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$servers->addColumn('Port', 'integer', array('default'=>'0','notnull'=>true,));
$servers->addColumn('Socket', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$servers->addColumn('Wrapper', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$servers->addColumn('Owner', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$slow_log->addColumn('start_time', 'datetime', array('default'=>'CURRENT_TIMESTAMP','notnull'=>true,));
$slow_log->addColumn('user_host', 'text', array('notnull'=>true,));
$slow_log->addColumn('query_time', 'time', array('notnull'=>true,));
$slow_log->addColumn('lock_time', 'time', array('notnull'=>true,));
$slow_log->addColumn('rows_sent', 'integer', array('notnull'=>true,));
$slow_log->addColumn('rows_examined', 'integer', array('notnull'=>true,));
$slow_log->addColumn('db', 'string', array('length'=>'512','notnull'=>true,));
$slow_log->addColumn('last_insert_id', 'integer', array('notnull'=>true,));
$slow_log->addColumn('insert_id', 'integer', array('notnull'=>true,));
$slow_log->addColumn('server_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$slow_log->addColumn('sql_text', 'text', array('notnull'=>true,));
$tables_priv->addColumn('Host', 'string', array('default'=>'','length'=>'60','notnull'=>true,'fixed'=>'1',));
$tables_priv->addColumn('Db', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$tables_priv->addColumn('User', 'string', array('default'=>'','length'=>'16','notnull'=>true,'fixed'=>'1',));
$tables_priv->addColumn('Table_name', 'string', array('default'=>'','length'=>'64','notnull'=>true,'fixed'=>'1',));
$tables_priv->addColumn('Grantor', 'string', array('default'=>'','length'=>'77','notnull'=>true,'fixed'=>'1',));
$tables_priv->addColumn('Timestamp', 'datetime', array('default'=>'CURRENT_TIMESTAMP','notnull'=>true,));
$tables_priv->addColumn('Table_priv', 'simple_array', array('default'=>'','notnull'=>true,));
$tables_priv->addColumn('Column_priv', 'simple_array', array('default'=>'','notnull'=>true,));
$time_zone->addColumn('Time_zone_id', 'integer', array('unsigned'=>true,'autoincrement'=>true,'notnull'=>true,));
$time_zone->addColumn('Use_leap_seconds', 'string', array('default'=>'N','notnull'=>true,));
$time_zone_leap_second->addColumn('Transition_time', 'bigint', array('notnull'=>true,));
$time_zone_leap_second->addColumn('Correction', 'integer', array('notnull'=>true,));
$time_zone_name->addColumn('Name', 'string', array('length'=>'64','notnull'=>true,'fixed'=>'1',));
$time_zone_name->addColumn('Time_zone_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$time_zone_transition->addColumn('Time_zone_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$time_zone_transition->addColumn('Transition_time', 'bigint', array('notnull'=>true,));
$time_zone_transition->addColumn('Transition_type_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$time_zone_transition_type->addColumn('Time_zone_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$time_zone_transition_type->addColumn('Transition_type_id', 'integer', array('unsigned'=>true,'notnull'=>true,));
$time_zone_transition_type->addColumn('Offset', 'integer', array('default'=>'0','notnull'=>true,));
$time_zone_transition_type->addColumn('Is_DST', 'boolean', array('unsigned'=>true,'default'=>'0','notnull'=>true,));
$time_zone_transition_type->addColumn('Abbreviation', 'string', array('default'=>'','length'=>'8','notnull'=>true,'fixed'=>'1',));
$user->addColumn('Host', 'string', array('default'=>'','length'=>'60','notnull'=>true,'fixed'=>'1',));
$user->addColumn('User', 'string', array('default'=>'','length'=>'16','notnull'=>true,'fixed'=>'1',));
$user->addColumn('Password', 'string', array('default'=>'','length'=>'41','notnull'=>true,'fixed'=>'1',));
$user->addColumn('Select_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Insert_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Update_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Delete_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Create_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Drop_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Reload_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Shutdown_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Process_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('File_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Grant_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('References_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Index_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Alter_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Show_db_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Super_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Create_tmp_table_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Lock_tables_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Execute_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Repl_slave_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Repl_client_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Create_view_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Show_view_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Create_routine_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Alter_routine_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Create_user_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Event_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Trigger_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('Create_tablespace_priv', 'string', array('default'=>'N','notnull'=>true,));
$user->addColumn('ssl_type', 'string', array('default'=>'','notnull'=>true,));
$user->addColumn('ssl_cipher', 'blob', array('notnull'=>true,));
$user->addColumn('x509_issuer', 'blob', array('notnull'=>true,));
$user->addColumn('x509_subject', 'blob', array('notnull'=>true,));
$user->addColumn('max_questions', 'integer', array('unsigned'=>true,'default'=>'0','notnull'=>true,));
$user->addColumn('max_updates', 'integer', array('unsigned'=>true,'default'=>'0','notnull'=>true,));
$user->addColumn('max_connections', 'integer', array('unsigned'=>true,'default'=>'0','notnull'=>true,));
$user->addColumn('max_user_connections', 'integer', array('unsigned'=>true,'default'=>'0','notnull'=>true,));
$user->addColumn('plugin', 'string', array('default'=>'','length'=>'64','notnull'=>false,'fixed'=>'1',));
$user->addColumn('authentication_string', 'text', array('notnull'=>false,));
$users->addColumn('uid', 'integer', array('unsigned'=>true,'default'=>'0','comment'=>'Primary Key: Unique user ID.','notnull'=>true,));
$users->addColumn('name', 'string', array('default'=>'','comment'=>'Unique user name.','length'=>'60','notnull'=>true,));
$users->addColumn('pass', 'string', array('default'=>'','comment'=>'User’s password (hashed).','length'=>'128','notnull'=>true,));
$users->addColumn('mail', 'string', array('default'=>'','comment'=>'User’s e-mail address.','length'=>'254','notnull'=>false,));
$users->addColumn('theme', 'string', array('default'=>'','comment'=>'User’s default theme.','length'=>'255','notnull'=>true,));
$users->addColumn('signature', 'string', array('default'=>'','comment'=>'User’s signature.','length'=>'255','notnull'=>true,));
$users->addColumn('signature_format', 'string', array('comment'=>'The filter_format.format of the signature.','length'=>'255','notnull'=>false,));
$users->addColumn('created', 'integer', array('default'=>'0','comment'=>'Timestamp for when user was created.','notnull'=>true,));
$users->addColumn('access', 'integer', array('default'=>'0','comment'=>'Timestamp for previous time user accessed the site.','notnull'=>true,));
$users->addColumn('login', 'integer', array('default'=>'0','comment'=>'Timestamp for user’s last login.','notnull'=>true,));
$users->addColumn('status', 'boolean', array('default'=>'0','comment'=>'Whether the user is active(1) or blocked(0).','notnull'=>true,));
$users->addColumn('timezone', 'string', array('comment'=>'User’s time zone.','length'=>'32','notnull'=>false,));
$users->addColumn('language', 'string', array('default'=>'','comment'=>'User’s default language.','length'=>'12','notnull'=>true,));
$users->addColumn('picture', 'integer', array('default'=>'0','comment'=>'Foreign key: file_managed.fid of user’s picture.','notnull'=>true,));
$users->addColumn('init', 'string', array('default'=>'','comment'=>'E-mail address used for initial account creation.','length'=>'254','notnull'=>false,));
$users->addColumn('data', 'blob', array('comment'=>'A serialized array of name value pairs that are related to the user. Any form values posted during user edit are stored and are loaded into the $user object during user_load(). Use of this field is discouraged and it will likely disappear in a future...','notnull'=>false,));
$users_acadia->addColumn('uid', 'integer', array('unsigned'=>true,'autoincrement'=>true,'notnull'=>true,));
$users_acadia->addColumn('name', 'string', array('default'=>'','length'=>'60','notnull'=>true,));
$users_acadia->addColumn('pass', 'string', array('default'=>'','length'=>'32','notnull'=>true,));
$users_acadia->addColumn('mail', 'string', array('default'=>'','length'=>'64','notnull'=>false,));
$users_acadia->addColumn('mode', 'boolean', array('default'=>'0','notnull'=>true,));
$users_acadia->addColumn('sort', 'boolean', array('default'=>'0','notnull'=>false,));
$users_acadia->addColumn('threshold', 'boolean', array('default'=>'0','notnull'=>false,));
$users_acadia->addColumn('theme', 'string', array('default'=>'','length'=>'255','notnull'=>true,));
$users_acadia->addColumn('signature', 'string', array('default'=>'','length'=>'255','notnull'=>true,));
$users_acadia->addColumn('signature_format', 'smallint', array('default'=>'0','notnull'=>true,));
$users_acadia->addColumn('created', 'integer', array('default'=>'0','notnull'=>true,));
$users_acadia->addColumn('access', 'integer', array('default'=>'0','notnull'=>true,));
$users_acadia->addColumn('login', 'integer', array('default'=>'0','notnull'=>true,));
$users_acadia->addColumn('status', 'boolean', array('default'=>'0','notnull'=>true,));
$users_acadia->addColumn('timezone', 'string', array('length'=>'8','notnull'=>false,));
$users_acadia->addColumn('language', 'string', array('default'=>'','length'=>'12','notnull'=>true,));
$users_acadia->addColumn('picture', 'string', array('default'=>'','length'=>'255','notnull'=>true,));
$users_acadia->addColumn('init', 'string', array('default'=>'','length'=>'64','notnull'=>false,));
$users_acadia->addColumn('data', 'text', array('notnull'=>false,));

//Table Indices
$columns_priv->setPrimaryKey(array('Host','Db','User','Table_name','Column_name'),'PRIMARY');
$db->setPrimaryKey(array('Host','Db','User'),'PRIMARY');
$db->addIndex(array('User'),'User');
$event->setPrimaryKey(array('db','name'),'PRIMARY');
$func->setPrimaryKey(array('name'),'PRIMARY');
$help_category->setPrimaryKey(array('help_category_id'),'PRIMARY');
$help_category->addUniqueIndex(array('name'),'name');
$help_keyword->setPrimaryKey(array('help_keyword_id'),'PRIMARY');
$help_keyword->addUniqueIndex(array('name'),'name');
$help_relation->setPrimaryKey(array('help_keyword_id','help_topic_id'),'PRIMARY');
$help_topic->setPrimaryKey(array('help_topic_id'),'PRIMARY');
$help_topic->addUniqueIndex(array('name'),'name');
$host->setPrimaryKey(array('Host','Db'),'PRIMARY');
$ndb_binlog_index->setPrimaryKey(array('epoch'),'PRIMARY');
$plugin->setPrimaryKey(array('name'),'PRIMARY');
$proc->setPrimaryKey(array('db','name','type'),'PRIMARY');
$procs_priv->setPrimaryKey(array('Host','Db','User','Routine_name','Routine_type'),'PRIMARY');
$procs_priv->addIndex(array('Grantor'),'Grantor');
$proxies_priv->setPrimaryKey(array('Host','User','Proxied_host','Proxied_user'),'PRIMARY');
$proxies_priv->addIndex(array('Grantor'),'Grantor');
$servers->setPrimaryKey(array('Server_name'),'PRIMARY');
$tables_priv->setPrimaryKey(array('Host','Db','User','Table_name'),'PRIMARY');
$tables_priv->addIndex(array('Grantor'),'Grantor');
$time_zone->setPrimaryKey(array('Time_zone_id'),'PRIMARY');
$time_zone_leap_second->setPrimaryKey(array('Transition_time'),'PRIMARY');
$time_zone_name->setPrimaryKey(array('Name'),'PRIMARY');
$time_zone_transition->setPrimaryKey(array('Time_zone_id','Transition_time'),'PRIMARY');
$time_zone_transition_type->setPrimaryKey(array('Time_zone_id','Transition_type_id'),'PRIMARY');
$user->setPrimaryKey(array('Host','User'),'PRIMARY');
$users_acadia->setPrimaryKey(array('uid'),'PRIMARY');
$users_acadia->addUniqueIndex(array('name'),'name');
$users_acadia->addIndex(array('access'),'access');
$users_acadia->addIndex(array('created'),'created');
$users_acadia->addIndex(array('mail'),'mail');